countries:
    de: D
    at: A
    pl: PL
    us: US
payments:
    transfer:
        id: 1
        name: Überweisung
    paypal:
        id: 5
        name: PayPal
    directebanking:
        id: 12
        name: Sofortüberweisung
