parameters:
    wk_afterbuy.afterbuy.url:
        xml:  "%afterbuy_xml_uri%"
        shop: "%afterbuy_shop_uri%"
    wk_afterbuy.afterbuy.params:
        partner_id:     "%afterbuy_partner_id%"
        partner_pass:   "%afterbuy_partner_pass%"
        user_id:        "%afterbuy_user_id%"
        user_pass:      "%afterbuy_user_password%"
        detail_level:   "%afterbuy_detail_level%"
        error_language: "%afterbuy_error_language%"

services:
    wk_afterbuy.afterbuy.connection:
        class: Wk\AfterbuyApi\Services\AfterbuyConnection
        calls:
            - [setApiUrls, ["%wk_afterbuy.afterbuy.url%"]]
            - [setParams, ["%wk_afterbuy.afterbuy.params%"]]
            - [setLogger, ["@logger"]]