parameters:
    wk_afterbuy.params:
        partner_id:     "%afterbuy_partner_id%"
        partner_pass:   "%afterbuy_partner_pass%"
        user_id:        "%afterbuy_user_id%"
        user_pass:      "%afterbuy_user_password%"

services:
    wk_afterbuy.shop_api.connection:
        class: Wk\AfterbuyApi\Services\AfterbuyConnection
        arguments: ["shopApiServiceDescription.json"]
        calls:
            - [setParams, ["%wk_afterbuy.params%"]]
    wk_afterbuy.shop_api:
        class: Wk\AfterbuyApi\Services\AfterbuyShopApi
        calls:
           - [setAfterbuyConnection, ["@wk_afterbuy.shop_api.connection"]]
           - [setLogger, ["@logger"]]
    wk_afterbuy.xml_api:
        class: Wk\AfterbuyApi\Services\AfterbuyXmlClient
        calls:
           - [setCredentials, ["%wk_afterbuy.params%"]]