parameters:
    wk_afterbuy.params:
        partner_id:     "%afterbuy_partner_id%"
        partner_pass:   "%afterbuy_partner_pass%"
        user_id:        "%afterbuy_user_id%"
        user_pass:      "%afterbuy_user_password%"

    wk_afterbuy.params.xml:
        baseurl:  "https://api.afterbuy.de/afterbuy/ABInterface.aspx"

services:
    wk_afterbuy.xml_api:
        class: Wk\AfterbuyApi\Services\AfterbuyXmlClient
        calls:
           - [setCredentials, ["%wk_afterbuy.params%"]]
           - [setUri, ["%wk_afterbuy.params.xml%"]]